server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/comparator-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

app:
  storage:
    path: C:\Users\Admin\Documents\node-projects\helloworld-data-comparator\data
  upload:
    max-file-size: 500MB
  cleanup:
    ttl-hours: 1
  comparison:
    timeout-minutes: 30
